### ISSUE TITLE
Issues with HDD Clicker

### ISSUE THREAD

**Issue by ConiKost** [skiselev/8088_bios#29]
I am not sure, if this is a hardware or software issue. But I noticed, when connecting a HDD Clicker [*] to my NuXT and using 0.9.8 or master, it behaves really strange. Upon pressing power on button, it starts to make noise, as if disk would do a never ending seek. Even during memory test. It stops doing that never ending seek, when I do start booting A or C. Then it behaves normally and only does some noise, when really disk is doing some work. I can only observe this on my NuXT. Other older devices, like some 486 stuff does not show that.

I also noticed, that the floppy access led (from my HxC emulator) is constantly blinking fast, same as the never ending noise from HDD clicker. All becomes "normal", when A or C starts to boot. Is this some sort of init, which polls something from power on?

* This is a small module, which is connected to HDD LED "man-in-the-middle" and simulates hard drive seek sounds with flash media. See: https://www.retrokits.de/index.php/hdd-clicker-v0-2/

**Comment by skiselev** [comment]
To be honest, I don't think that it is a software issue. If I understand correctly HDD Clicker simply connects to the HDD activity LED, and makes sounds whenever it is active. NuXT, depending on the version, has either a XT-CF-Lite (NuXT 1.x) or XT-IDE (NuXT 2.x) integrated on the motherboard. If I am not mistaken, in both cases it connects the DASP signal from IDE or CF card to the header, through a buffer or inverter.
No idea about HxC... but also looks like some kind of glitch. Normally, on the floppy drive, the LED lights up when the drive is selected. That will not happen until the BIOS will select the drive and turn on the motor, e.g., when booting up, or otherwise accessing the floppy disk
There is a slight chance that your power supply or system introduce some kind of noise... Although in this case I'd think that the whole system would be unstable

**Comment by ConiKost** [comment]
Indeed. I just gave a try for GlaBIOS and is has the same behauvior, so it's nothing software related. Thanks!
