### ISSUE TITLE
book8088 BIOS Source Code

### ISSUE THREAD

**Issue by 0cjs** [skiselev/8088_bios#35]
I've heard that there were complaints about GPL violations with the book8088 BIOS. To make examining the evidence easier, I've imported the source code a friend received after ordering one into a branch in my fork repo: [`vendor/book8088`](https://github.com/0cjs/skiselev_8088_bios/tree/vendor/book8088). (I have not myself ordered one.)

As the parent I used the latest commit in the original code that was before the date in the new code's `config.inc`, so a diff with the parent should turn up mainly just the vendor changes.

If you have questions about this import, it's better to contact me in text chat via Telegram (`@cjs_cynic`) or Discord (`cjs#6537`).

**Comment by skiselev** [comment]
The BIOS code is based on commit https://github.com/skiselev/8088_bios/commit/027f3f130fc60dadfac087f334a0b95d02819363  from August 8th, 2022.

There are no significant changes in the code, such as a new functionality being implemented or any significant rewrites. It is mostly just comments, deletions, and minor changes.

**Summary of the BIOS Changes**

- In some files, including the modified files below, my name and the GPL license were removed. Interestingly some files still contain my name and the GPL license
- bios.asm (the main file) - A lot of code removed, e.g FE2010A chipset support, Xi 8088 specific second interrupt controller support, PS/2 mouse support, checking and printing serial ports, parallel ports, floppy drives configuration. There is an interesting change regarding the PPI Port B (61h) register. On IBM it is a read-write port, apparently on Book8088 it is a write-only port (see Hardware Notes below). So instead reading and modifying it, BIOS simply writes the new value. That's mostly used for speaker control
- keyboard.inc (keyboard BIOS functions) - AT-style keyboard and FE2010A chipset specific code removed
- at_kbc.inc (AT-style keyboard controller support) - many comments in Chinese were added. I don't see any functionality changes. The surprising thing is that Book8088 does not appear to use an AT-style keyboard controller. I don't really know why they went through the trouble of documenting it. Perhaps it was used in an earlier prototype? The commented out "%define AT_KEYBOARD" seems to suggest that, because the rest of unused defines were simply erased
- messages.inc (strings that BIOS prints on the screen) - the copyright info replaced and the license info removed. uses "CPU" instead of "Main Processor", "FPU" instead of "Mathematics Co-processor", several changes to the processor names, removed strings related to the BIOS setup (absent in Book8088)
- cpu.inc (CPU type detection, FPU detection, turbo mode switching) - FE2010A chipset support deleted
- scancode.inc (keyboard scancodes translation table) - several comments in Chinese were added
- sound.inc (boot melody) - code updates to avoid reading PPI Port B (61h) 
- delay.inc (well, delay subroutine) - comments in Chinese added, along with "SHAN" (the name of the person modifying the code?).

**Book8088 Hardware Notes**
- In addition to the 8088 CPU and the 8087 FPU, it uses an original 8284 clock generator, 8288 bus controller, 8237 DMA controller, 8259 PIC, and 8253 PIT. It has been reported that Book8088 is shipped with 82xx ICs made using NMOS technology (Intel calls it HMOS). Replacing these ICs with CMOS 82Cxx counterparts significantly improves the battery life
- Most of the discrete logic functionality of an XT motherboard is integrated in an Atmel ATF1508AS CPLD
- The CGA controller functionality is implemented using two Atmel ATF1508AS CPLDs and the original 6845 CRT controller
- A microcontroller is used to implement the XT keyboard. It is interfaced directly to the XT motherboard logic CPLD
- The system uses two EPROMs: one 27C512 for the BIOS, and one 27C256 for the CGA font
- The system memory uses one 512KB SRAM and one 128 KB SRAM chip. CGA uses a 32 KB SRAM for the video RAM
- System supports 8 MHz Turbo. The turbo switching is implemented in the keyboard controller, and it does not seem to have software Turbo control
- 8255 PPI Port B - I/O port 61h is emulated using the CPLD. It appears that only bits 1 and 0 are read/write, the rest of the bits return 34h (001101xxb) when read

**Comment by skiselev** [comment]
Official Book8088 support has been added to 8088 BIOS. See https://github.com/skiselev/8088_bios/commit/ebcc587a16f84bff40e3a0daf06d85a6b13d0248
