### ISSUE TITLE
PC Speaker Compatibility

### ISSUE THREAD

**Issue by oblende** [skiselev/8088_bios#47]
Seems like a silly thing to ask about, but I couldn't figure out where else to ask as it seems hardware and BIOS related. 

So I had decided to learn assembly language in DOS using the Book 8088 with the help of the book "Assembly Language Primer for the IBM PC & XT." Things were going good until I got to the section involving sound using the PC speaker, then everything stopped working. I then tried as many examples from the internet on using the PC speaker, including the beep code from your  BIOS and all failed. The frustrating part is that other applications including the beep command seem to work fine. In desperation I then figured out how to get Virtualbox to passthrough the PC speaker, and the programs I was having troubble with worked. It still does not explain how your bios and various applications is able to make sound. Could you explain how I'm screwing my code up, please? Also I'm using the msa2 assembler, so I commented out all the MASM specific parts of the code. I may still end up using MASM so I figure writing the MASM parts in the comments was the best way to learn even if I wasn't using that assembler. Sorry if it makes the code harder to read.

`
    ;SIREN--Uses Timer2 to run speaker
    ;  features siren effect
    ;
    ;**************************************************
    ;prognam segment	;define code segment

    ;--------------------------------------------------
    ;main:	;proc far	;main part of program

	;assume	cs:prognam

	;org 0x100	;first address

    start:		;starting execution address

    ;start 1/pitch at FFFFh
	    mov	bx,0x0ffff	;set 1/pitch in BX

    ;sound the tone
	    mov	al,0xb6 	;put magic number
	    out	0x43,al		;  into timer2
    tone:	mov	ax,bx		;move 1/pitch into AX
	    out	0x42,al		;LSB into timer2
	   mov	al,ah		;MSB to AL, then
	    out	0x42,al		;  to timer2
	    in	al,0x61		;read port B into AL
	    or 	al,0x03		;turn on bits 0 and 1
	   out	0x61,al		;to turn on speaker

    ;increase the pitch and wait a bit
	    dec	bx		;increase the pitch
	    mov	cx,100		;set up wait loop
    wait:	loop 	wait		;wait
	    jmp	tone		;go do new tone

    ;main	endp	;end of main part of program
    ;---------------------------------------------------
    ;
    ;prognam ends	;end of code segment
    ;***************************************************
    ;
	    ;end	start	;end assembly
`

**Comment by skiselev** [comment]
This is obviously not quite a bug or an issue in the BIOS, and has nothing to do you the PC speaker compatibility :)

Anyhow, let me try to help you.

There is one document that you'd want to take a look at. It is the [8254 Programmable Interval Timer (PIT) datasheet](https://www.scs.stanford.edu/10wi-cs140/pintos/specs/8254.pdf). Particularly, check page number 6 there.

There are two components that are used for sound generation in the IBM PC:
- The 8254 PIT mentioned above. It has 3 counters (0 to 2). Counter 2 is used for sound generation
- Bits 0 and 1 of the I/O port 0x61
  - Bit 0 controls GATE input of the counter 2 of the PIT. When set to 0, it will inhibit counting.
  - Bit 1 is connected to an AND gate, and it will disable sound when set 0. Or enable when set to 1.
- You could generate sounds using PIT or by operating the AND gate directly.

A bit about 8254 PIT and its addressing in IBM PC:
- Port 0x43 is the 8254 PIT command word register. It configures the count mode for the timer and other things
- Port 0x42 is the count for the counter 2. The port you write to set the initial count, or read to get the current count, if you like.
- There is no magic about command word values. They are documented in the datasheet page 6 linked above. For example, the 0xB6 value is 10110110 in binary, where:
  - Two most significant bits (10) is the counter select, and they select counter 2 (10 binary)
  - Next two bits (11) select the mode where you read/write the least significant byte first followed by the most significant byte
  - Next three bits (011) select counter mode 3 - square wave. That's what you typically need for sound generation
  - Finally the least significant bit (0) selects binary counting mode. The other option is binary coded decimal (BCD) mode
 
Why my code doesn't work?

I suspect it happens because of this: "For each Counter, the Control Word must be written before the initial count is written." 
Try moving your "tone:" label two lines up, before you write the "magic number".
Also, it might be a good idea to disable speaker before you reprogram the PIT.
Add something like:

in al,0x61
and al,0xFC
out al,0x61

Of course, you can take the [sound.inc](https://github.com/skiselev/8088_bios/blob/master/src/sound.inc) from this BIOS, and just modify it a bit.

**Comment by skiselev** [comment]
I still don't understand what happened with your assembler ;)
How come or al,0x03 got assembled as or al,[bp+di]?
Either that assembler is trash or you're not doing something right ;)
